-- PostgreSQL schema for the social-login MVP.

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  nickname VARCHAR(30) NOT NULL,
  trust_score INTEGER NOT NULL DEFAULT 50,
  living_alone_years INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_users_email UNIQUE (email),
  CONSTRAINT uk_users_nickname UNIQUE (nickname),
  CONSTRAINT chk_users_trust_score CHECK (trust_score BETWEEN 0 AND 100),
  CONSTRAINT chk_users_living_alone_years CHECK (living_alone_years >= 0)
);

CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  CONSTRAINT uk_categories_name UNIQUE (name)
);

CREATE TABLE places (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kakao_place_id VARCHAR(255) NOT NULL,
  name VARCHAR(150) NOT NULL,
  address VARCHAR(255),
  latitude NUMERIC(10,7) NOT NULL,
  longitude NUMERIC(10,7) NOT NULL,
  phone VARCHAR(30),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_places_kakao_place_id UNIQUE (kakao_place_id)
);

CREATE INDEX idx_places_location ON places (latitude, longitude);

CREATE TABLE tips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  place_id BIGINT NOT NULL,
  category_id BIGINT NOT NULL,
  title VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  visited_at DATE,
  valid_until TIMESTAMPTZ NOT NULL,
  is_filtered BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_tips_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_tips_place FOREIGN KEY (place_id) REFERENCES places (id),
  CONSTRAINT fk_tips_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE INDEX idx_tips_user_created ON tips (user_id, created_at);
CREATE INDEX idx_tips_place_created ON tips (place_id, created_at);
CREATE INDEX idx_tips_category_created ON tips (category_id, created_at);
CREATE INDEX idx_tips_valid_until ON tips (valid_until);

CREATE TABLE user_follows (
  follower_id BIGINT NOT NULL,
  following_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (follower_id, following_id),
  CONSTRAINT fk_user_follows_follower FOREIGN KEY (follower_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_user_follows_following FOREIGN KEY (following_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT chk_user_follows_self CHECK (follower_id <> following_id)
);

CREATE INDEX idx_user_follows_following ON user_follows (following_id);

CREATE TABLE tip_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tip_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_tip_comments_tip FOREIGN KEY (tip_id) REFERENCES tips (id) ON DELETE CASCADE,
  CONSTRAINT fk_tip_comments_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_tip_comments_tip_created ON tip_comments (tip_id, created_at);
CREATE INDEX idx_tip_comments_user ON tip_comments (user_id);

CREATE TABLE tip_scraps (
  user_id BIGINT NOT NULL,
  tip_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, tip_id),
  CONSTRAINT fk_tip_scraps_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_tip_scraps_tip FOREIGN KEY (tip_id) REFERENCES tips (id) ON DELETE CASCADE
);

CREATE INDEX idx_tip_scraps_tip ON tip_scraps (tip_id);

CREATE TABLE tip_reactions (
  user_id BIGINT NOT NULL,
  tip_id BIGINT NOT NULL,
  is_like BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, tip_id),
  CONSTRAINT fk_tip_reactions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_tip_reactions_tip FOREIGN KEY (tip_id) REFERENCES tips (id) ON DELETE CASCADE
);

CREATE INDEX idx_tip_reactions_tip_like ON tip_reactions (tip_id, is_like);

CREATE TABLE refresh_token_sessions (
  id VARCHAR(255) PRIMARY KEY,
  user_id BIGINT NOT NULL,
  token_hash VARCHAR(64) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,
  device_info VARCHAR(255),
  last_used_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT uk_refresh_token_sessions_token_hash UNIQUE (token_hash),
  CONSTRAINT fk_refresh_token_sessions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_token_sessions_user_id ON refresh_token_sessions (user_id);
